version: "3.8"
services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  web:
    build:
      context: .
      dockerfile: Dockerfile-Ngnix
    ports:
      - 8080:80
